---
- name: Set ansible repository
  become: yes
  apt_repository:
    repo: "ppa:ansible/ansible"

- name: Install current ansible
  become: yes
  apt:
    pkg:   "{{ item }}"
    state: installed
  with_items: 
    -  ansible

- name: Generate ansible.cfg
  template:
    src:  "ansible.j2"
    dest: "{{ ansible_env.HOME }}/ansible.cfg"
