# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
    num_nodes = (ENV['NUM_NODES'] || 1).to_i
    num_nodes.times do |n|
        config.vm.define :"vx#{n+1}" do |node|
            #node.vm.box  = "CumulusCommunity/cumulus-vx"
            node.vm.box  = "cumlus-vx-2.5.5"
            #node.vm.network :private_network, ip: "192.168.1.#{n+11}/24"
            #node.vm.network :private_network, ip: "192.168.2.#{n+11}/24"
            #node.vm.network :private_network, ip: "192.168.3.#{n+11}/24"
            #node.vm.network :private_network, ip: "192.168.4.#{n+11}/24"
            node.ssh.forward_agent = true
        end
    end

    config.vm.provision :ansible do |ansible|
        ansible.host_key_checking = false
        ansible.playbook = "site.yaml"
        ansible.raw_arguments = [
            "--user=vagrant"
        ]
        ansible.verbose = "v"
    end

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 512]
        vb.customize ["modifyvm", :id, "--cpus", 1]
    end
end
